### PR TITLE
Fix #3617 (Incorrect use of `std::unique_ptr<char>`) mixing `new[]` with `delete`

### LINKED ISSUE #3617: Incorrect use of std::unique_ptr<char> instead of std::unique_ptr<char[]> for array allocation
In CodeLite/winprocess.cpp, there's a potential memory deallocation bug due to the incorrect use of std::unique_ptr<char> to manage a dynamically allocated character array.

Problematic code (line 180 as of current commit):

```
char* chBuf = new char[65536 + 1]; // 64K should be sufficient buffer
memset(chBuf, 0, 65536 + 1);

std::unique_ptr<char> sp(chBuf); // Incorrect - this calls delete instead of `delete[]`
```
This will result in undefined behavior when the unique_ptr goes out of scope, since it calls delete on an array allocated with new[].

Suggested fix:

Replace with std::unique_ptr<char[]>

### PR DESCRIPTION
**Pull request by Jarod42**
closes #3617

### CODE REVIEW

**Comment by Jarod42** [comment]
msys2 now fails because of new CMake 4 on msys2. Unrelated to that PR

File: CodeLite/winprocess.cpp [hunk 1]
```diff
@@ -173,26 +173,22 @@ WinProcess::~WinProcess() {}
 
 bool WinProcess::Read(wxString& buff)
 {
-    DWORD dwRead;
-    DWORD dwMode;
-    DWORD dwTimeout;
-    char* chBuf = new char[65536 + 1]; // 64K should be sufficient buffer
-    memset(chBuf, 0, 65536 + 1);
-
-    std::unique_ptr<char> sp(chBuf);
```
Comment (eranif) [inline CodeLite/winprocess.cpp:182]: wouldn't be sufficient just to change this into: 

```c++
std::unique_ptr<char[]> sp(chBuf);
```

**Review by eranif — APPROVED** [review]

**Review by eranif — APPROVED** [review]

File: CodeLite/winprocess.cpp (hunk 1 above)
Comment (Jarod42) [reply CodeLite/winprocess.cpp:182]: It was possible too. `std::vector` seems simpler/more appropriate IMO.
